codecov:
   branch:developcoverage:
  range: 70...100 status: patch:default:target:"30%"
        paths:"!test/"
    project:default:target:autopaths: "!test/"syntax:
        target: autopaths: "libsolidity/analysis"flags: syntax
      tests:target:autopaths: "test/"comment:layout: "reach, diff, flags"
